SURFscz/SRAM-deploy

- environments/vm/group_vars/lb.yml
- roles/firewall/templates/ip4tables.j2
Make sure COmanae can reach the ldap server.
> Fix firewall

- roles/satosa/tasks/main.yml
- roles/satosa/templates/attribute_filter.yaml.j2
- roles/satosa/templates/proxy_conf.yaml.j2
Added the (empty) attribute_filter microservice to default deploy. It will run, but will pass everything for now.
> Attribute Filter

- roles/ldap/tasks/main.yml
- roles/ldap/templates/enable_syncprov.ldif.j2
My First LDAP.  Fingers crossed...
> enable synprov provider for ldap

- Vagrantfile
- roles/comanage/defaults/main.yml
- roles/comanage/tasks/main.yml
- roles/comanage_plugins/tasks/main.yml
Added tasks in Comanage roles to activate the Service & Service Token
plugins.
> Added Plugins for Service & Service Tokens

- roles/satosa/defaults/main.yml
- roles/satosa/templates/saml2_backend.yaml.j2
- roles/satosa/templates/saml2_frontend.yaml.j2
Enable Jinja looping for satosa mdui language elements and contacts.
> Fix Satosa mdui config in loops

- roles/satosa/templates/consent.yaml.j2
This change locks all consent attributes and effectively renders the consent screen an inform.
> Lock all consent attributes = inform

- environments/vm/group_vars/proxy.yml
- roles/satosa/defaults/main.yml
- roles/satosa/tasks/main.yml
This feature can safely be merged. Until SCZ/SATOSA merges feature-split-microservices, all microservices will just be overwritten: nothing breaks.
> Split microservices from SATOSA repo

- Vagrantfile
- environments/vm/group_vars/client.yml
- roles/client-base/templates/config.php.j2
- roles/client-google-idp/defaults/main.yml
- roles/client-google-idp/tasks/main.yml
Fixes Google-IdP syslog warnings
https://www.pivotaltracker.com/story/show/156873198
> Fix google-idp warnings

- README.md
- remove-docker-images
- scripts/remove-docker-images
Nu draai ik op mijn systeem geen debian, maar openSUSE. Ik ben zo vrij geweest om om de README.md hierop wat aan te passen. In de README geeft ik aan dat dit wel 'experimantal' is, om niet een te stellige claim neer te leggen.
> Update README.md with openSUSE Tumbleweed info.

- roles/satosa/templates/custom_logging_service.yaml.j2
Custom logging microservice was not in sync with internal attributes renaming.
> Fix satosa logging config

- roles/metadata/tasks/main.yml
- roles/metadata/templates/create_metadata
An attempt to make metadata creation stable. Xalan is much less memory hungry than xsltproc.
> Replace xsltproc with xalan on meta

- roles/client-base/templates/saml20-idp-hosted.php.j2
- roles/satosa/defaults/main.yml
- roles/satosa/tasks/main.yml
- roles/satosa/templates/attribute_filter.yaml.j2
- roles/satosa/templates/internal_attributes.yaml.j2
- roles/satosa/templates/metainfo.yaml.j2
- roles/satosa/templates/proxy_conf.yaml.j2
And minor template indention fixes.
> Add test registration authority

- roles/metadata/files/nohide.xsl
- roles/metadata/files/nologo.xsl
- roles/metadata/files/nosc.xsl
- roles/metadata/tasks/main.yml
- roles/metadata/templates/create_metadata.j2
- roles/metadata/templates/metadata.timer.j2
- roles/pyff/templates/mdq.fd.j2
Fixes unwanted R&S CoCo IdP filtering, removes hide-from-discovery entity category
> Fix eduGAIN IdP's metadata feed

- roles/satosa/templates/internal_attributes.yaml.j2
Ugly hack around pysaml lib FriendlyName conversion.
> Add FriendlyNames

- roles/ldap_clients/defaults/main.yml
- roles/ldap_clients/tasks/client.yml
- roles/ldap_clients/templates/lsc.xml.j2
and allow for different uid/gidNumber sequence start
> Update LSC template for sshPublicKey 

- roles/satosa/templates/metainfo.yaml.j2
metainfo micro_service now consumes registration authority exceptions from conf
> metainfo micro_service config changed

- roles/satosa/tasks/main.yml
- roles/satosa/templates/saml2_backend.yaml.j2
- roles/satosa/templates/saml2_frontend.yaml.j2
- roles/satosa/templates/saml2_mirrorbackend.yaml.j2
- roles/satosa/templates/saml2_mirrorfrontend.yaml.j2
This PR fixes the RequestedAttributes behaviour.
> Add IgnorePolicy configuration to Satosa

- roles/satosa/templates/internal_attributes.yaml.j2
https://www.pivotaltracker.com/n/projects/1988811/stories/161634370
> Rename surname internal to sn

- roles/ldap/tasks/main.yml
- roles/ldap/templates/enable_memberof.ldif.j2
- roles/ldap/templates/enable_memberof_1mdb.ldif.j2
- roles/ldap_clients/files/sczGroup.ldif
- roles/ldap_clients/tasks/main.yml
- roles/ldap_clients/templates/enable_memberof_2mdb.ldif.j2
- roles/ldap_clients/vars/ldap.yml
Untested. I **hope** this covers the first part of the change.
> Enable memberOf Overlay for first mdb

- roles/syslog-client/tasks/main.yaml
Add upgradeable counter script
> Feature collectd metrics

- roles/satosa/defaults/main.yml
- roles/satosa/files/gen_metadata
- roles/satosa/tasks/main.yml
- roles/satosa/templates/custom_alias.yaml.j2
- roles/satosa/templates/custom_logging_service.yaml.j2
- roles/satosa/templates/fb_satosa.yml.j2
- roles/satosa/templates/gen_metadata.j2
The SATOSA equivalent of #157 
https://github.com/SURFscz/SATOSA-micro_services/commit/3b0c58fde3f4883e9ab05c84fc7f2dc03a8ce92c will break without this PR
> Separate SATOSA config/input/output from venv

- environments/vm/group_vars/vm.yml
- environments/vm/secrets/all.yml
- roles/client-microsoft-idp/tasks/main.yml
- roles/client-orcid-idp/tasks/main.yml
- roles/client-orcid-idp/templates/orcid-sb.conf.j2
- scripts/check-idempotency-status
Niet functioneel getest (wel Ansible deploy getest).
Heeft orcid_sb_client_id en orcid_sb_client_secret nodig. Heb het simplesamlphp vhost index nummer van MS auth en Orcid sandbox verwisseld zodat de Orcid's bij elkaar zitten.
> Add Orcid Sandbox OP

- roles/client-oidc-rp/templates/oidc.conf.j2
https://www.pivotaltracker.com/story/show/164828574
> Add idpcountry/idpname to OIDC RP requested attributes

- roles/satosa/templates/db_attribute_store.yaml.j2
- roles/satosa/templates/sbs_attribute_store.yaml.j2
This PR configures the new SCZ microservices attributestores blacklists
> Add db/sbs_attribute_store blacklists

- roles/proxy_mysql/files/copersoncol.sql
Add modified column to zone_services instead of to zone_people
> Fixed column changes for zone-services

- roles/apt/defaults/main.yml
- roles/https_haproxy/defaults/main.yml
- roles/https_haproxy/files/ocsp.sh
- roles/https_haproxy/handlers/main.yml
- roles/https_haproxy/tasks/main.yml
- roles/https_haproxy/templates/ocsp-letsencrypt.j2
- roles/https_haproxy/templates/ocsp.service.j2
- roles/https_haproxy/templates/ocsp.timer.j2
- roles/tls_letsencrypt/tasks/main.yml
This adds OCSP stapling to buster/http2 branch
> Enable OCSP stapling in haproxy

- roles/lsc/defaults/main.yml
- roles/lsc/tasks/main.yml
- roles/lsc/templates/plsc.service.j2
- roles/lsc/templates/plsc.yml.j2
Create ordered-flat LDAP structure
> Deploy ordered-flat LDAP structure

- README.md
- environments/vm/group_vars/client.yml
- environments/vm/group_vars/vm.yml
- provision.yml
- roles/client-2fa/files/google2urn.php
- roles/client-2fa/handlers/main.yml
- roles/client-2fa/tasks/main.yml
- roles/client-2fa/templates/2fa.conf.j2
- roles/client-base/templates/authsources.php.j2
- roles/client-base/templates/saml20-idp-hosted.php.j2
- roles/client-microsoft-idp/tasks/main.yml
- roles/client-orcid-idp/tasks/main.yml
- roles/pyff/templates/mdq.fd.j2
- scripts/check-idempotency-status
> Add simple SCZ 2FA test IdP

- roles/metadata/templates/create_metadata.j2
Fixes https://www.pivotaltracker.com/story/show/171666218
> Remove all directories older than 7 days

- roles/lb_haproxy/templates/haproxy.cfg.j2
- roles/pyff/templates/nginx-pyff.conf.j2
Ratelimit is too tight and I had several CSP headers issues in both pyFF and Satosa.
> Weaken ratelimit and fix several CSP headers

- roles/pam_websso/tasks/main.yml
- roles/pam_websso_daemon/tasks/main.yml
> Fixes pam-websso build

- roles/pam_websso/tasks/main.yml
- roles/pam_websso_daemon/defaults/main.yml
- roles/pam_websso_daemon/tasks/main.yml
- roles/pam_websso_daemon/templates/websso-daemon.service.j2
Migrate websso daemon to python3, seperate directory
libpam-python seems to move slowly to python3 https://sourceforge.net/p/pam-python/tickets/5/
> Migrate websso-daemon to python3, own directory

- docker/docker-compose.yml.py
- environments/vm/group_vars/all.yml
- roles/sbs/defaults/main.yml
Makes it easy to inspect SBS (invitation) mails
> Add MailHog docker for mail inspection

- .github/workflows/main.yml
- ansible.cfg
Remove mitogen conf from ansible.cfg file to prevent failures on local deploy
> Fix mitogen cfg

- docker/docker-compose.yml.py
- environments/vm/group_vars/vm.yml
- environments/vm/inventory
Completely removes proxy from inventory and docker-compose
> Remove proxy from inventory

- environments/vm/group_vars/all.yml
- roles/lb_haproxy/templates/haproxy.cfg.j2
Needs new iprange.internal definition in environment
> Add rate-limit exception for internal network

- docker/docker-compose.yml.py
- environments/vm/group_vars/all.yml
- start-vm
This adds a separate SBS redis host and sets configuration on vm groupvars
> Fix external redis_host reference for SBS

- scripts/sbs-login.py
This fixes the Selenium test deprecation warnings
> Fix selenium deprecation warnings

- .github/workflows/main.yml
- .gitignore
- ci-runner/seed.py.in
- environments/ci/group_vars/sbs.yml
- environments/ci/secrets/all.yml
- environments/vm/group_vars/sbs.yml
- environments/vm/secrets/all.yml
- scripts/sbs-login.py
- start-vm
Fixes build login-test and ci-runner test
> Fix login test

- ci-runner/admin.json
- ci-runner/features/ci.feature
- ci-runner/features/steps/ci.py
- ci-runner/student.json
This change enables broader user claims testing against a file-based json structure of the expected output.
> Add file-based user claims test scenario

- README.md
- environments/vm/secrets/all.yml
- requirements.yml
- roles/oidc-op/defaults/main.yml
- roles/oidc-op/templates/config_op.yaml.j2
This needs https://github.com/IdentityPython/oidc-op/pull/200 so wait for that to be merged and tagged.
> Fixes oidcop pairwise and public sub to return persistent uid

- ci-runner/features/steps/ci.py
Fixes CI-runner runs for SBS behave test
> Replace all deprecated find_element_by calls

- roles/oidc-op/tasks/main.yml
- roles/oidc-op/templates/config_op.json.j2
- roles/oidc-op/templates/oidc-op.service.j2
- roles/oidc-op/templates/sram_users.json.j2
Fixes https://github.com/SURFscz/SRAM-deploy/issues/323 and https://github.com/SURFscz/SRAM-deploy/issues/322
> Improve OIDC-OP

- .github/workflows/issues.yml
- .github/workflows/project.yml
- README.md
- scripts/project-logs
- scripts/project-versions
- surf-deploy
Collateral damage of an attempt at getting rid of SCZ-deploy debris
> Remove all remaining mentions of SCZ-deploy

- environments/ci/group_vars/all.yml
- environments/ci/secrets/all.yml
- environments/vm/group_vars/all.yml
- environments/vm/secrets/all.yml
- roles/sbs/defaults/main.yml
- roles/sbs/tasks/main.yml
- roles/sbs/templates/alembic.ini.j2
First attempt at fixing https://github.com/SURFscz/SRAM-deploy/issues/290
> Move migration to SBS ansible role and add migration user

- roles/sbs/tasks/main.yml
SBS user needs TRIGGER to complete seed from interface
> Add TRIGGER priv for SBS user (needed for seed)

- roles/sbs/templates/config.yml.j2
Replace MySQL driver, depends on https://github.com/SURFscz/SBS/pull/393
> Replace pymysql with mysqldb driver

- ci-runner/seed.py.in
- environments/vm/group_vars/all.yml
- roles/sbs/tasks/main.yml
- roles/sbs/templates/alembic.ini.j2
- roles/sbs/templates/config.yml.j2
This should fix ```pip install mysqlclient``` on SBS
> Add libmariadb-dev-compat to SBS depdendencies for mysqlclient

- docker/docker-compose.yml.py
- environments/ci/secrets/all.yml
- environments/vm/secrets/all.yml
- roles/sbs/templates/config.yml.j2
Deploy Redis with password and configure SBS to use it
> Configure redis with password

- roles/sbs/templates/sbs-nginx.j2
More options https://nginx.org/en/docs/http/ngx_http_gzip_module.html
> Add gzip support for SBS static js/css files

- roles/ldap_monitor/files/sram-ldapmonitor.conf
- roles/ldap_monitor/handlers/main.yml
- roles/ldap_monitor/tasks/main.yml
- roles/ldap_monitor/templates/ldapmonitor.sh.j2
Add a UserParameter for Zabbix ldapmonitoring and make status file readable for zabbix user
> Improve the ldapmonitor handling for Zabbix usage

- ci-runner/admin.json
- ci-runner/student.json
- roles/ldap_monitor/files/ldifparser.py
- roles/ldap_monitor/tasks/main.yml
- roles/plsc/files/plscmonitor.py
- roles/plsc/files/sram-plscmonitor.conf
- roles/plsc/handlers/main.yml
- roles/plsc/tasks/main.yml
- roles/zabbix-agent/tasks/main.yml
- scripts/sbs-login.py
This adds a monitor to the plsc role
> Add service timing monitor to plsc

- environments/vm/group_vars/vm.yml
- environments/vm/secrets/users.yml
- roles/ldap/tasks/main.yml
- scripts/sbs-login.py
Needs final decision on condition (group)
> Conditionally add LDAP admins

- roles/demo-sp/templates/rp.php.j2
I didn't know what SameSite should be set to, so I resorted to None for the moment.
> Set RP SameSite cookie to None

- ci-runner/features/environment.py
- roles/oidc-op/templates/sram_users.json.j2
- scripts/sbs-login.py
admin's voperson_external_affilation attribute wasn't scoped in our local OIDC Test OP.
> Scope Test-OP admin voperson_external_affilation attribute

- .gitignore
- .vscode/settings.json
- environments/vm/secrets/all.yml
- roles/plsc/defaults/main.yml
- roles/plsc/templates/plsc.yml.j2
- roles/tools/tasks/main.yml
- roles/tools/tasks/www.yml
- roles/tools/templates/index.html.j2
- roles/tools_contacts/defaults/main.yml
- roles/tools_contacts/handlers/main.yml
- roles/tools_contacts/tasks/main.yml
- roles/tools_contacts/templates/contacts.yml.j2
- roles/tools_contacts/templates/sram_contacts.service.j2
- roles/tools_contacts/templates/sram_contacts.timer.j2
> Generate lists of contacts on tools.sram.surf.nl

- roles/demo-sp/files/auth.php
Update lists of known attributes and present them in order of (wiki) appearance.
> Update lists of known attributes

- environments/docker/group_vars/demo1.yml
- provision.yml
- roles/demo-weblogin/defaults/main.yml
- roles/demo-weblogin/handlers/main.yml
- roles/demo-weblogin/tasks/main.yml
- roles/demo-weblogin/templates/weblogin-cleanup.service.j2
- roles/demo-weblogin/templates/weblogin-cleanup.timer.j2
> Add weblogin to demo1

- roles/sram_monitor/templates/sram-monitor.conf.j2
- start-vm
Add SBS login monitor test and timestamping of the results.
Please beware that this also changes the Zabbix check!!
> Add SBS login monitoring and timestamp

- roles/demo-apache/templates/apache.conf.j2
https://httpd.apache.org/docs/trunk/ssl/ssl_howto.html#ciphersuites
> Fix demo1 weak TLS config

- roles/lb_haproxy/templates/haproxy.cfg.j2
> Remove XSS header from haproxy

- roles/docker_sbs/defaults/main.yml
- roles/docker_sbs/tasks/main.yml
- roles/sbs/defaults/main.yml
- roles/sbs/tasks/main.yml
Adds an explicit setting for column_case_sensitive in community.mysql.mysql_user module
> Add column_case_sensitive option

- roles/demo-apache/templates/apache.conf.j2
> Prevent Index listing on IP based access

- roles/http_redirect/templates/http-redirect.conf.j2
- roles/lb_haproxy/templates/haproxy.cfg.j2
- roles/nginx/files/security_headers
> Set referrer policy to same-origin

- provision.yml
- roles/demo-apache/templates/apache.conf.j2
- roles/demo-wordpress/tasks/main.yml
Revert (comment) the demo1 CSP headers, they break everything
> Revert demo1 CSP headers

- roles/docker_plsc/templates/plsc.yml.j2
A leftover from the big sbs/sbs-server rename commit
> Fix docker-plsc config

- ci-runner/admin.json
- ci-runner/features/steps/ci.py
- ci-runner/student.json
- roles/ci-test/templates/index.php.j2
- scripts/sbs-login.py
Add refreshToken tests to SRAM-deploy CI behave tests
> Add refreshToken tests

- roles/simplesamlphp/defaults/main.yml
The role is included in:
- test-idp
- surfstar-idp
- ci-test
- demo-sp
Which means a redeploy of
- bhr13
- test (CI test docker)
> Bump simplSAMLphp version

- environments/ci/group_vars/sbs.yml
- environments/docker/group_vars/container.yml
- environments/vm/group_vars/sbs.yml
- roles/docker_sbs/defaults/main.yml
- roles/sbs/templates/config.yml.j2
Make SBS OIDC scopes configurable. Closes #565
> Make sbs oidc scopes configurable
