SURFscz/SRAM-deploy

- roles/mail/handlers/main.yml
- roles/mail/tasks/mailleaf.yml
- roles/mail/templates/mailname.j2
- roles/mail/templates/nullmailer.remotes.j2
nullmailer implements local queuing, so it won't instantly fail when the
smtp proxy is down for a little while
> use nullmailer instead of ssmtp

- provision.yml
Variables usage is preferred by Ansible to have spaces around them.
> Confirm to Ansible syntax

- roles/oidc2samlidp/templates/google_backend.yaml.j2
The var changed to google_client_id, but oidc2samlidp is deprecated anyway... if we leave it in, this way it isn't broken at least.
> Fix deprecated oidc2samlidp

- environments/vm/group_vars/comanage.yml
- roles/comanage_idp/tasks/main.yml
- roles/satosa/files/internal_attributes.yaml
- roles/satosa/tasks/main.yml
- roles/satosa/templates/attribute_filter.yaml.j2
- roles/satosa/templates/custom_uid.yaml.j2
- roles/satosa/templates/proxy_conf.yaml.j2
Lets satosa create cmuid, filter all outgoing attributes except to comanage. Let comanage consume cmuid as REMOTE_USER.
> Create Comanage CMuid, filter attributes

- ansible.cfg
- provision.yml
Before, only 5 would run in parallel, which is kind of annoying when
deploying 6 hosts...
> Run all (up to 20) hosts in parallel

- roles/satosa/templates/attribute_filter_post.yaml.j2
- roles/satosa/templates/attribute_filter_pre.yaml.j2
It seems comanage moved from http to https entityID. This breaks satosa entityID based attribute filtering.
> Fix comanage filtering entityID

- roles/client-saml-idp/templates/saml20-sp-remote.php.j2
- roles/satosa/templates/saml2_backend.yaml.j2
This adds encrypted assertion demonstration between Satosa Saml2Backend and simplesamlphp Satosa non-transparent SP configuration
> Add example encrypted assertion setup for Saml2Backend

- roles/client-base/templates/authsources.php.j2
This tests new code in satosa custom_uid microservice without breaking existing uid's
> Send out correctly xml-formatted epti test attributevalue

- roles/cmservice/files/logrotate_cmservice
- roles/cmservice/files/rsyslog_cmservice.conf
- roles/cmservice/tasks/main.yml
- roles/cmservice/templates/cmservice.service.j2
- roles/pyff/files/logrotate_pyffd
- roles/pyff/tasks/main.yml
- roles/satosa/files/logrotate_satosa
- roles/satosa/tasks/main.yml
This PR adds long overdue logrotate configuration for proxy services and redirects cmservice logs to it's own logs.
> Rotate proxy daemon logs

- roles/ldap/tasks/main.yml
- roles/ldap/vars/ldap.yml
Added voPerson objectclass. Apparently this is supported in COmanage 3.2.0 and I needed this for testing an upstream PR. I figured we would need this in the deploy as well at some point, although the LdapFixedProvisioner needs updates for that.
> Added voPerson objectclass (exportable in COmanage 3.2.0)

- README.md
- roles/ldap/handlers/main.yml
LDAP handler name still contained 'systemd' instead of 'systemctl'.
README.md wrongly stated that there are 5 instead of 6 VMs.
> Fixed an ldap handler name and README

- Vagrantfile
- docker/Dockerfile
Deze patch verwijdert de static SSH key in de Dockerfile en gebruikt --build-arg om de huidige pub ssh key van vagrant te krijgen.
> Use --build-arg for setting SSH pub key.

- roles/comanage_plugins/defaults/main.yml
- roles/comanage_plugins/vars/comanage_plugins.yml
This introduces the SamlSource plugin in the default SCZ COmanage registry deploy. The SamlSource plugin does not work properly until PR#7 of the SCZ comanage registry has been included.
> Added SamlSource OIS plugin from SCZ repository

- docker/Dockerfile
Although the Travis CPU load was fixed, getty's were still spawned for Linux hosts that needed a tty console locally. This is fixed by removing the multi-user.target.wants/getty.target
> Disable getty spawning in docker VM's

- roles/pam_websso/templates/pam_websso.json.j2
- roles/pam_websso_daemon/templates/websso_daemon.json.j2
I changed the responsability for creating websso-url to the websso-daemon, which is the logical place to do it. This commit reflects the necessary changes in the pam suite configuration(s)
> Fix configuration changes in pam-websso

- roles/pam_websso/tasks/main.yml
pam-websso can't be installed in virtualenv (at least not the PAM module) and python-saml has a hard dependancy on dm.xmlsec.binding which needs to compile cython bindings against a pip'ed version of python-lxml. The debian package of lxml contains an invalid etree_api.h header file (wrong name).
> Attempt at streamlining pam-websso pip installation

- roles/metadata/files/idps.xsl
idps.xsl contained a mistake that created invalid metadata for some IDPSSO/SPSSO entities, this PR fixes that plus removes the useless signature on the fly.
> Fix metadata xslt IdP filtering

- environments/vm/group_vars/vm.yml
- provision.yml
- roles/pam_websso/tasks/main.yml
- roles/pam_websso/templates/pam_websso.json.j2
PAM WebSSO is now 100% HTTP transport only.
> Adjust ansible roles for new PAM WebSSO HTTP transport

- roles/satosa/templates/r_and_s_acl.yaml.j2
R&S was still configured to look at old surname internal attribute.
> Fixes R&S filter sn internal attribute mapping

- roles/pam_websso/defaults/main.yml
- roles/pam_websso/tasks/main.yml
- roles/pam_websso/templates/libnss-ldap.conf.j2
- roles/pam_websso/templates/nslcd.conf.j2
- roles/pam_websso/templates/pam-websso.j2
- roles/pam_websso/templates/pam_ldap.secret.j2
- roles/pam_websso/templates/pam_websso.json.j2
This PR migrates libnss-ldap based nss to libnss-ldapd, so that ldaps connections work:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=579647
> Migrate libnss-ldap to libnss-ldapd

- roles/pam_websso/tasks/main.yml
For some obscure reason my latest docker deploy had the passwd: and group: lines end on 'systemd' instead of 'compat', so the find/replace nsswitch.conf tasks failed to add 'ldap' at the end.
Also, sshd 'ChallengeResponseAuthentication yes' doesn't seem to be default anymore, or I missed it because of manual installation attempts before.
> Fix nsswitch.conf update tasks

- roles/syslog-server/files/curator.yml
- roles/syslog-server/files/curator_actions.yml
- roles/syslog-server/tasks/main.yaml
Indices can now be pruned (30 days) using
```
curator --config /etc/elasticsearch/curator.yml --dry-run /etc/elasticsearch/curator_actions.yml
```
> Add ES-curator config to prune indices

- roles/syslog-client/defaults/main.yml
- roles/syslog-client/files/scz-logging.service
- roles/syslog-client/files/scz-logging.timer
- roles/syslog-client/files/upgradeable
- roles/syslog-client/handlers/main.yml
- roles/syslog-client/tasks/main.yaml
- roles/syslog-client/templates/collectd.conf.j2
- roles/syslog-client/templates/iptables.sh.j2
- roles/syslog-server/files/logstash.conf
- roles/syslog-server/tasks/main.yaml
Since metricbeats doesn't potentially fullill our requirements I tried a collectd version of the metrics collection. I need collectd package on the server for /usr/share/collectd/types.db and disable the service, but we might want to collect metrics from stats server as well, which bites the disabling of the service?
> Add collectd metrics logging

- environments/vm/group_vars/all.yml
- provision.yml
- roles/zabbix-agent/files/count_upgradeable
- roles/zabbix-agent/handlers/main.yaml
- roles/zabbix-agent/tasks/main.yaml
- roles/zabbix-agent/templates/default.conf.j2
This requires ```pip install zabbix-api``` on the **_host_** from where the ansible deploy is ran.
> Client Zabbix-agent package and configuration

- roles/pyff/defaults/main.yml
- roles/pyff/tasks/main.yml
- roles/pyff/templates/mdq.fd.j2
By default metadata will live in /opt/pyff/metadata
> Separate metadata from pyFF venv

- environments/vm/group_vars/proxy.yml
- roles/satosa/defaults/main.yml
- roles/satosa/files/gen_metadata
- roles/satosa/tasks/main.yml
- roles/satosa/templates/custom_alias.yaml.j2
- roles/satosa/templates/custom_logging_service.yaml.j2
- roles/satosa/templates/gen_metadata.j2
- roles/satosa/templates/saml2_backend.yaml.j2
- roles/satosa/templates/saml2_frontend.yaml.j2
- roles/satosa/templates/saml2_mirrorbackend.yaml.j2
- roles/satosa/templates/saml2_mirrorfrontend.yaml.j2
As we now rely on a fixed version of pysaml2, we can remove the empty mapper dir work-around. This PR also fixes correct default SATOSA branch.
> Remove SATOSA mapper dir work-around

- roles/firewall/tasks/main.yml
This was previously blocked only for Docker configuration. This fix is non-backward compatible in the sense that it would enable firewalling if docker were to be used in a test or pilot environment, but that is not (yet) the case.
> Fix to prevent configuration of a firewall in the case of VMs. 

- roles/satosa/templates/attribute_filter.yaml.j2
SBS needs raw, unfiltered  IdP attributes, just like COManage.
> Add SBS server clientID to attribute filter whitelist

- roles/apt/tasks/main.yml
- roles/zabbix-agent/files/restart_kernel
- roles/zabbix-agent/files/restart_services
- roles/zabbix-agent/tasks/main.yml
This adds a common needrestart package and two helper scripts for Zabbix
> Add restart trigger in Zabbix

- roles/https_haproxy/tasks/main.yml
- roles/https_haproxy/templates/crt-list.txt.j2
- roles/https_haproxy/templates/haproxy.cfg.j2
- roles/slp/tasks/main.yml
This PR enables http2 on haproxy for Debian buster
> Enable haproxy http2 on frontend

- docker/docker-compose.yml.py
- environments/vm/group_vars/ldap.yml
- environments/vm/group_vars/vm.yml
- roles/pam_websso_daemon/handlers/main.yml
- roles/pam_websso_daemon/tasks/main.yml
- roles/pam_websso_daemon/tasks/nginx.yml
- roles/pam_websso_daemon/templates/nginx-pam.conf.j2
This fixes the pam-websso demo, but still requires ```/etc/nslcd.conf``` to contain an existing basedn to resolve existing users in ldap e.g:
```
base dc=flat,dc=https://sp-test.scz-vm.net/saml/module.php/saml/sp/metadata.php/default-sp,dc=services,dc=vnet
```
This is analogue to what a conventional SSH service would need to configure.
> Fix pam-websso

- roles/satosa/templates/saml2_backend.yaml.j2
- roles/satosa/templates/saml2_mirrorbackend.yaml.j2
- roles/satosa/templates/saml2_mirrorfrontend.yaml.j2
For some reason, SATOSA sometimes falls back on MirroredFrontend configuration to check incoming authnRequests. This failed because of the incorrect mdq endpoint in that frontend (although barely used). Linked to PR #119 Adding trailing slashes while we're at it.
> Fix mirrorfrontend mdq url

- roles/ldap_services/templates/set_root_credentials.ldif.j2
Deployed and checked:
```
root@ldap2:/etc/ldap/slapd.d/cn=config# cat olcDatabase\=\{1\}mdb.ldif 
dn: olcDatabase={1}mdb
objectClass: olcDatabaseConfig
objectClass: olcMdbConfig
olcDatabase: {1}mdb
olcDbDirectory: /var/lib/ldap
olcLastMod: TRUE
olcDbCheckpoint: 512 30
olcDbIndex: objectClass eq
olcDbIndex: cn,uid eq
olcDbIndex: uidNumber,gidNumber eq
olcDbIndex: member,memberUid eq
olcDbIndex: entryUUID eq
...
```
> Add index for entryUUID

- roles/basic/tasks/main.yml
This PR aims to add the self-signed VM wildcard cert to the ca-certificates.crt bundle for all back-end machines.
> Add VM wildcard cert to ca-certificates.crt

- roles/pyff-metadata/defaults/main.yml
- roles/pyff-metadata/tasks/main.yml
- roles/pyff-metadata/templates/idp_feed.fd.j2
This adds the ability to add extra entityID's at will, without re-deploying pyff-metadata
> Add metadata source dir to pyff-metadata feed

- roles/metadata/templates/index.html.j2
This adds some extra text and links to explain what metadata to downoad for SP's and IdP's connecting to SRAM using the eduTEAMS proxy.
> Fix index landingpage for eduTEAMS SRAM proxy metadata endpoints

- roles/lb_haproxy/templates/haproxy.cfg.j2
Resolves https://github.com/SURFscz/SRAM-deploy/issues/293
Failed attempt logs look like this:
`Aug 24 12:01:37 lb haproxy[10787]: 172.20.1.1:58326 [24/Aug/2022:12:01:37.268] ldap_ldap_636~ ldap_ldap_636/<NOSRV> -1/-1/+177 +0 PR 1/1/0/0/3 0/0`
They have `<NOSRV>` instead of a valid backend server.
> Log failed LDAP connection attempts

- environments/docker/group_vars/container.yml
- environments/vm/group_vars/vm.yml
- roles/lb_haproxy/templates/haproxy.cfg.j2
Fix the bug that HAproxy wouldn't request the correct hostname from the backend server.  In case of the docker setup, this caused traefik to serve the wrong health endpoint.
> Fix haproxy SBS health check

- roles/ci-runner/tasks/main.yml
We never added Chromium(-*) to the required packages, but it defenately needs to be installed when reprovisioning bhr12.
Probably installed by hand during testing?
> Fix ci-runner pkgs

- roles/docker_ldap/tasks/main.yml
Expose LDAP container 1389 to localhost:389 on the docker host
> Confine LDAP port expose to localhost

- environments/docker/group_vars/container.yml
- roles/docker_sbs/defaults/main.yml
- roles/sbs/defaults/main.yml
- roles/sbs/templates/config.yml.j2
Improve manual suspension testing of local container deploy.
By assigning `0` to `allowed_inactive_period_days` and `-1` to `reminder_suspend_period_days` we can notify and suspend users in two  consecutive suspend cron runs, including the mails sent to the user when the `last_login_date` of a user is set in the past (manual db action).
> Improve suspension policy for testing

- roles/lb_haproxy/templates/haproxy.cfg.j2
- start-vm
Ansible-galaxy collection syntax has changed a little, so it never updated stale packges.
HAproxy was broken on container deploy, because it can not handle maxconn * FD_SETSIZE filehandles (or something along those lines). https://github.com/docker-library/haproxy/issues/180
fd_hard_limit is not available in our version, so had to reduce global.maxconn.
> Fix ansible and haproxy for containers
